@startuml Supply Line


!$cla = "#ffffff"
!$clb = "#333333"
!$clstatebg = "#eeeeee"
!$clnotebg = "#dc0451"
!$fntsz = 16
!$cornrsz = $fntsz/2

skinparam shadowing false
skinparam roundcorner $cornrsz
skinparam BackgroundColor $cla
skinparam ArrowColor $clb

skinparam default {
    FontColor $clb
    FontSize $fntsz
    FontName Fira Sans
    MonospacedFontName Fira Sans
}

skinparam SequenceBox {
    BackgroundColor #ddd
    BorderColor #333
}

skinparam Actor {
    BackgroundColor $cla
    BorderColor $clb
}

skinparam Node {
    BackgroundColor $cla
    BorderColor $clb
}

skinparam Interface {
    BackgroundColor $cla
    BorderColor $clb
}

skinparam Usecase {
    BackgroundColor $cla
    BorderColor $clb
}

skinparam Rectangle {
    BackgroundColor $cla
    BorderColor $clb
}

skinparam Note {
    BackgroundColor $clnotebg
    BorderColor $clnotebg
    FontColor $cla
}

skinparam Package {
    BackgroundColor $cla
    BorderColor $clb
}

skinparam Queue {
    BackgroundColor $cla
    BorderColor $clb
}

skinparam Database {
    BackgroundColor $cla
    BorderColor $clb
}

'Note that in some versions of PlantUML the Background Col and the Border col on Collections is switched (so you might need to switch these around below)
skinparam Collections {
    BackgroundColor $clb
    BorderColor $cla
}

skinparam Participant {
    BackgroundColor $clb
    BorderColor $clb
    FontColor $cla
    FontStyle bold
}

skinparam Sequence {
    LifeLineBorderColor $clb
}

skinparam State {
    AttributeFontColor $clb
    FontColor $clb
    AttributeFontSize $fntsz
    FontSize $fntsz
    AttributeFontName Fira Sans
    FontName Fira Sans
    StartColor green
    EndColor red
    BorderColor $clb
    BackgroundColor $clstatebg
    RoundCorner $cornrsz
}

skinparam shadowing false

/' ********** EDIT BELOW HERE ********** '/

box "Public"
actor "Vulnerable Person" as Customer
actor "Local Community" as LocalCommunity
end box

box "Social Media Platform"
entity "Social Media Platform API" as SocMedPAPI
actor "Social Media Group Admin" as SocMedGA
actor "Social Media Group User" as SocMedGU
end box

box "Supply Line"
entity "Supply Line Phone Service" as SLPhone
entity "Supply Line CRM" as SLCRM
actor "Supply Line Admin" as SLAdmin
actor "Supply Line User" as SLUser
end box

box "Multual Aid Group / Trust Verifier"
actor "Trust Verifier" as TrustVerify
entity "gov.uk Identity Verify" as IDVerification
end box

box "Government / Local Authority"
entity "Services" as GovernmentServices
actor "Trusted Individual" as GovTrustIndividual
end box

box "Law Enforcement"
actor "Local Police" as LocalPolice
end box

box "Communication Operators"
entity "Communication Data Sources" as CommsData
end box

== Social Media Group Admin wants to set up an incoming Phone service ==
autonumber
SocMedGA -> SLCRM : SocMed Admin signs up for an account at SupplyLine
SLCRM -> SocMedGA : Informs new user that their account 'Requires \nTrust and ID Verification' status, tells User, provides a trust code.
SocMedGA -> SLCRM : Provides Identity Verification (using gov.uk 'Identity' or similar)
alt Trust Verification method - via Supply Line
    SLCRM -> SLUser : Notification to Supply Line user to verify trust of sign up.
    SLUser -> TrustVerify : Verify new user with trusted source (e.g. DBS/DSS, etc).
    TrustVerify -> SLCRM : Confirm to Supply Line that the user is trusted.
else Trust Verification method - via manual route to Trust Verifier
    SLCRM -> SocMedGA : Informs new user of a Trust Verification code.
    SocMedGA -> TrustVerify : Tells Local Trust Verifier the code to authorise them.
    TrustVerify -> SLCRM : Uses code provided and their trusted id to authorise user.
    SLCRM -> SocMedGA : Identity is verified
end
SLCRM -> SocMedGA : Informs SocMed Admin that trust has been identified
SocMedGA -> SLCRM : Logs in and sets up profile.
SocMedGA -> SLCRM : Connects account to SocMedia Page/Group (Facebook, etc)
SocMedGA -> SLCRM : Requests phone number, is assigned this, sets up IVR based on template.
SocMedGA -> SocMedGU : Informs everyone in the group that they have a new Supply Line Service
SocMedGA -> LocalCommunity : Informs vulnerable people via postcards in \ncommunity mail drop. (template for card available \nfrom Supply Line)

== Initial Contact from Vulnerable Person ==
autonumber

Customer -> SLPhone : Customer phones the Supply Line phone line



@enduml